name: Build Android APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Cache build deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: android-deps-${{ runner.os }}-${{ hashFiles('gradle/**', 'gradlew*', 'gradle.properties', '*.gradle*') }}
          restore-keys: |
            android-deps-${{ runner.os }}-
      - name: Use dummy google-services json
        run: mv androidApp/src/google-services-dummy.json androidApp/src/google-services.json
      - name: Build and Test
        run: ./gradlew :androidApp:assembleDebug testDebugUnitTest testAndroidHostTest jvmTest lintDebug
        env:
          GITHUB_ACTOR: ${{ secrets.READ_PACKAGES_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: pebble-index-compat-debug-apk
          path: androidApp/build/outputs/apk/debug/*.apk
          if-no-files-found: error
